# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ooCIW_Ufa2Xwyxo0VhUj5iAwtQ-2wube
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB

iris_data.isna().sum()

iris = load_iris()

iris_data = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_data

x = iris.data
y = iris.target

print("Feature names:", iris.feature_names)
print("Target names:", iris.target_names)